import { useEffect, useState } from 'react';
import type { SceneId } from '../types';

export const SUPPORTED_LOCALES = ['en', 'de', 'fr', 'it', 'es', 'cs', 'pl'] as const;
export type SupportedLocale = typeof SUPPORTED_LOCALES[number];
export const LOCALE_STORAGE_KEY = 'audio-visualizer-locale';

const EN = {
  appSubtitle: 'Browser-native motion lab', previewLive: 'Preview is live', localFirst: 'Local-first', exportRunning: 'MP4 export · running', exportReady: 'MP4 export · ready', exportWebCodecs: 'MP4 export · WebCodecs',
  visual: 'Visual', style: 'Style', audio: 'Audio', layout: 'Layout', importExport: 'Import / export', present: 'Present', sceneModules: 'Scene modules', paletteMood: 'Palette and mood', localMp3Source: 'Local MP3 source', canvasProfile: 'Canvas profile', projectInterchange: 'Project interchange', cleanCaptureMode: 'Clean capture mode', quickControls: 'Quick controls', closeSettings: 'Close {name} settings', live: 'Live', response: 'Response', energy: 'Energy', overallLift: 'Overall visual lift', sensitivity: 'Sensitivity', audioResponse: 'Audio response curve', motion: 'Motion', animationTempo: 'Animation tempo', density: 'Density', detailParticles: 'Detail and particles', glow: 'Glow', bloomIntensity: 'Bloom intensity', originalScene: 'Původní', randomScene: 'Náhodně', resetScene: 'Reset scene', randomizeScene: 'Randomize scene', activateScene: 'Activate {name}', deactivateScene: 'Deactivate {name}', activeLayers: '{count}/3 visualizations active', layerLimitReached: 'Maximum of three visualizations is active.', noActiveLayers: 'No visualization is active.',
  projectName: 'Project name', noAudioSelected: 'No audio selected', silencePreview: 'The preview is running in silence.', chooseLocalMp3: 'Choose local MP3', resetAudio: 'Reset audio', audioBrowserHint: 'Audio stays in the browser and is never uploaded.',
  layoutCopy: 'Choose a platform canvas for the live workspace and offline export.', active: 'Active', landscape: 'Landscape', portrait: 'Portrait', square: 'Square',
  exportCopy: 'Deterministic offline MP4 export uses WebCodecs (H.264 + AAC) and mp4-muxer. If the browser does not support the exact combination, export stops with an explicit error.', fps: 'FPS', lengthSeconds: 'Length (s)', quality: 'Quality', high: 'High', balanced: 'Balanced', low: 'Low', reducedMotion: 'Reduced Motion', exporting: 'Exporting…', exportMp4: 'Export MP4', cancelExport: 'Cancel export', downloadMp4: 'Download MP4 ({size} KB)', exportFailed: 'Export failed.', exportCancelled: 'Export cancelled.',
  presentationCopy: 'Hide the chrome and expand the live canvas for OBS, screen recording or a clean presentation.', enterPresentation: 'Enter presentation mode', escapeHint: 'Press Escape to close this panel or leave presentation mode.', showControls: 'Show controls', presentationMode: 'Presentation mode', exitPresentation: 'Exit presentation mode',
  canvasAria: 'Live audio visualizer preview', fpsTarget: '60 FPS target', loadMp3: 'Load an MP3 to make the scene react', previewAlreadySilence: 'The preview is already running in silence.', moduleVersion: 'module v1.0', audioTransport: 'Audio transport', localAudioSource: 'Local audio source', chooseMp3Begin: 'Choose an MP3 to begin', previousPosition: 'Previous position', playAudio: 'Play audio', pauseAudio: 'Pause audio', nextPosition: 'Next position', playbackPosition: 'Playback position', volume: 'Volume', stageNote: 'Audio stays in your browser. Project controls persist locally; no upload or account is required.', language: 'Language', languageSelector: 'Language selector',
  spectrumName: 'Spectrum', spectrumDescription: 'Crisp frequency columns that follow the pulse.', threeDSpectrumName: '3D Spectrum', threeDSpectrumDescription: 'A room-perspective Spectrum with mirrored walls and fading Ghost trails.', waveformName: 'Waveform', waveformDescription: 'A luminous ribbon with an organic audio contour.', orbitalName: 'Orbital', orbitalDescription: 'Layered particles and rings expanding with low frequencies.', fluidGlowName: 'Fluid Glow', fluidGlowDescription: 'Slow clouds of light for atmospheric mixes.', cosmicName: 'Cosmic Kaleidoscope', cosmicDescription: 'A WebGL2 kaleidoscope driven by audio energy.', layeredCirclesName: 'Layered Circles', layeredCirclesDescription: 'Audio-reactive stacked circles inspired by the client reference.',
  auroraName: 'Aurora', auroraDescription: 'Cool mint with a warm signal', emberName: 'Ember', emberDescription: 'Copper, coral and midnight', monoName: 'Monochrome', monoDescription: 'Quiet graphite and electric white', oceanName: 'Deep ocean', oceanDescription: 'Blue depth with a violet edge', rubyName: 'Rubín', rubyDescription: 'Ruby red and rose pink', emeraldName: 'Emerald', emeraldDescription: 'Emerald green with deep teal', iceColdName: 'Ice cold', iceColdDescription: 'Arctic blue, white and violet',
  youtube: 'YouTube', tiktok: 'TikTok', instagram: 'Instagram', custom: 'Custom', languageEnglish: 'English', languageGerman: 'German', languageFrench: 'French', languageItalian: 'Italian', languageSpanish: 'Spanish', languageCzech: 'Czech', languagePolish: 'Polish',
} as const;
export type TranslationKey = keyof typeof EN;

type Catalog = Record<TranslationKey, string>;
const makeCatalog = (overrides: Partial<Catalog>): Catalog => ({ ...EN, ...overrides });

export const TRANSLATIONS: Record<SupportedLocale, Catalog> = {
  en: makeCatalog({}),
  de: makeCatalog({ appSubtitle: 'Browser-native Motion-Lab', previewLive: 'Vorschau ist aktiv', localFirst: 'Lokal zuerst', visual: 'Visual', style: 'Stil', audio: 'Audio', layout: 'Layout', present: 'Präsentieren', sceneModules: 'Szenenmodule', paletteMood: 'Palette und Stimmung', localMp3Source: 'Lokale MP3-Quelle', quickControls: 'Schnellsteuerung', energy: 'Energie', sensitivity: 'Empfindlichkeit', live: 'Live', response: 'Antwort', overallLift: 'Gesamter visueller Hub', audioResponse: 'Audio-Reaktionskurve', animationTempo: 'Animationstempo', detailParticles: 'Details und Partikel', bloomIntensity: 'Bloom-Intensität', moduleVersion: 'Modul v1.0', chooseMp3Begin: 'MP3 zum Starten wählen', motion: 'Bewegung', density: 'Dichte', glow: 'Leuchten', resetScene: 'Szene zurücksetzen', projectName: 'Projektname', noAudioSelected: 'Kein Audio ausgewählt', silencePreview: 'Die Vorschau läuft stumm.', chooseLocalMp3: 'Lokale MP3 wählen', resetAudio: 'Audio zurücksetzen', language: 'Sprache', languageSelector: 'Sprachauswahl', fpsTarget: 'Ziel: 60 FPS', loadMp3: 'MP3 laden und Szene reagieren lassen', previewAlreadySilence: 'Die Vorschau läuft bereits stumm.', localAudioSource: 'Lokale Audioquelle', playAudio: 'Audio abspielen', pauseAudio: 'Audio pausieren', previousPosition: 'Vorherige Position', nextPosition: 'Nächste Position', playbackPosition: 'Wiedergabeposition', volume: 'Lautstärke', stageNote: 'Audio bleibt im Browser. Projektsteuerung wird lokal gespeichert; kein Upload und kein Konto erforderlich.', spectrumName: 'Spektrum', spectrumDescription: 'Klare Frequenzsäulen im Takt.', threeDSpectrumName: '3D-Spektrum', threeDSpectrumDescription: 'Perspektivischer Raum mit Spiegelwänden und verblassenden Ghost-Spuren.', waveformName: 'Wellenform', waveformDescription: 'Leuchtendes Band mit organischer Audiokontur.', orbitalName: 'Orbital', orbitalDescription: 'Teilchen und Ringe, die mit tiefen Frequenzen wachsen.', fluidGlowName: 'Fließendes Leuchten', fluidGlowDescription: 'Langsame Lichtwolken für atmosphärische Mixe.', cosmicName: 'Kosmisches Kaleidoskop', cosmicDescription: 'Audio-gesteuertes WebGL2-Kaleidoskop.', auroraName: 'Aurora', auroraDescription: 'Kühles Mint mit warmem Signal', emberName: 'Glut', emberDescription: 'Kupfer, Koralle und Mitternacht', monoName: 'Monochrom', monoDescription: 'Ruhiges Graphit und elektrisches Weiß', oceanName: 'Tiefer Ozean', oceanDescription: 'Blaue Tiefe mit violettem Rand', landscape: 'Querformat', portrait: 'Hochformat', square: 'Quadrat', high: 'Hoch', balanced: 'Ausgewogen', low: 'Niedrig', reducedMotion: 'Weniger Bewegung', languageEnglish: 'Englisch', languageGerman: 'Deutsch', languageFrench: 'Französisch', languageItalian: 'Italienisch', languageSpanish: 'Spanisch', languageCzech: 'Tschechisch', languagePolish: 'Polnisch' }),
  fr: makeCatalog({ appSubtitle: 'Laboratoire de mouvement natif du navigateur', previewLive: 'Aperçu actif', localFirst: 'Local d’abord', visual: 'Visuel', style: 'Style', audio: 'Audio', layout: 'Mise en page', present: 'Présenter', sceneModules: 'Modules de scène', paletteMood: 'Palette et ambiance', quickControls: 'Contrôles rapides', energy: 'Énergie', sensitivity: 'Sensibilité', live: 'En direct', response: 'Réponse', overallLift: 'Élévation visuelle globale', audioResponse: 'Courbe de réponse audio', animationTempo: 'Tempo de l’animation', detailParticles: 'Détails et particules', bloomIntensity: 'Intensité de la lueur', moduleVersion: 'module v1.0', chooseMp3Begin: 'Choisir un MP3 pour commencer', motion: 'Mouvement', density: 'Densité', glow: 'Lueur', resetScene: 'Réinitialiser la scène', projectName: 'Nom du projet', noAudioSelected: 'Aucun audio sélectionné', silencePreview: 'L’aperçu fonctionne en silence.', chooseLocalMp3: 'Choisir un MP3 local', resetAudio: 'Réinitialiser l’audio', language: 'Langue', languageSelector: 'Sélecteur de langue', fpsTarget: 'Objectif 60 FPS', loadMp3: 'Chargez un MP3 pour faire réagir la scène', previewAlreadySilence: 'L’aperçu fonctionne déjà en silence.', playAudio: 'Lire l’audio', pauseAudio: 'Mettre en pause', previousPosition: 'Position précédente', nextPosition: 'Position suivante', playbackPosition: 'Position de lecture', volume: 'Volume', stageNote: 'L’audio reste dans le navigateur. Les contrôles sont conservés localement ; aucun envoi ni compte requis.', spectrumName: 'Spectre', spectrumDescription: 'Colonnes de fréquence nettes au rythme du signal.', threeDSpectrumName: 'Spectre 3D', threeDSpectrumDescription: 'Salle en perspective avec murs miroir et traînées Ghost.', waveformName: 'Forme d’onde', waveformDescription: 'Ruban lumineux au contour audio organique.', orbitalName: 'Orbital', orbitalDescription: 'Particules et anneaux amplifiés par les basses.', fluidGlowName: 'Lueur fluide', fluidGlowDescription: 'Nuages lents de lumière pour des mix atmosphériques.', cosmicName: 'Kaléidoscope cosmique', cosmicDescription: 'Kaléidoscope WebGL2 piloté par l’audio.', auroraName: 'Aurore', auroraDescription: 'Menthe fraîche et signal chaleureux', emberName: 'Braise', emberDescription: 'Cuivre, corail et nuit', monoName: 'Monochrome', monoDescription: 'Graphite doux et blanc électrique', oceanName: 'Océan profond', oceanDescription: 'Profondeur bleue et bord violet', landscape: 'Paysage', portrait: 'Portrait', square: 'Carré', high: 'Élevée', balanced: 'Équilibrée', low: 'Basse', reducedMotion: 'Mouvement réduit', languageEnglish: 'Anglais', languageGerman: 'Allemand', languageFrench: 'Français', languageItalian: 'Italien', languageSpanish: 'Espagnol', languageCzech: 'Tchèque', languagePolish: 'Polonais' }),
  it: makeCatalog({ appSubtitle: 'Laboratorio di movimento nativo del browser', previewLive: 'Anteprima attiva', localFirst: 'Prima locale', visual: 'Visuale', style: 'Stile', audio: 'Audio', layout: 'Layout', present: 'Presenta', sceneModules: 'Moduli scena', paletteMood: 'Palette e atmosfera', quickControls: 'Controlli rapidi', energy: 'Energia', sensitivity: 'Sensibilità', live: 'Live', response: 'Risposta', overallLift: 'Sollevamento visivo globale', audioResponse: 'Curva di risposta audio', animationTempo: 'Tempo dell’animazione', detailParticles: 'Dettagli e particelle', bloomIntensity: 'Intensità del bagliore', moduleVersion: 'modulo v1.0', chooseMp3Begin: 'Scegli un MP3 per iniziare', motion: 'Movimento', density: 'Densità', glow: 'Bagliore', resetScene: 'Reimposta scena', projectName: 'Nome progetto', noAudioSelected: 'Nessun audio selezionato', silencePreview: 'L’anteprima funziona in silenzio.', chooseLocalMp3: 'Scegli MP3 locale', resetAudio: 'Reimposta audio', language: 'Lingua', languageSelector: 'Selettore lingua', fpsTarget: 'Obiettivo 60 FPS', loadMp3: 'Carica un MP3 per far reagire la scena', playAudio: 'Riproduci audio', pauseAudio: 'Metti in pausa', previousPosition: 'Posizione precedente', nextPosition: 'Posizione successiva', playbackPosition: 'Posizione di riproduzione', volume: 'Volume', stageNote: 'L’audio resta nel browser. I controlli del progetto sono salvati localmente; nessun upload o account richiesto.', spectrumName: 'Spettro', spectrumDescription: 'Colonne di frequenza nitide al ritmo del segnale.', threeDSpectrumName: 'Spettro 3D', threeDSpectrumDescription: 'Stanza prospettica con pareti specchiate e scie Ghost.', waveformName: 'Forma d’onda', waveformDescription: 'Nastro luminoso con contorno audio organico.', orbitalName: 'Orbitale', orbitalDescription: 'Particelle e anelli che crescono con le basse frequenze.', fluidGlowName: 'Bagliore fluido', fluidGlowDescription: 'Nuvole lente di luce per mix atmosferici.', cosmicName: 'Caleidoscopio cosmico', cosmicDescription: 'Caleidoscopio WebGL2 guidato dall’audio.', auroraName: 'Aurora', auroraDescription: 'Menta fredda con segnale caldo', emberName: 'Brace', emberDescription: 'Rame, corallo e mezzanotte', monoName: 'Monocromo', monoDescription: 'Grafite discreto e bianco elettrico', oceanName: 'Oceano profondo', oceanDescription: 'Profondità blu con bordo viola', landscape: 'Orizzontale', portrait: 'Verticale', square: 'Quadrato', high: 'Alta', balanced: 'Bilanciata', low: 'Bassa', reducedMotion: 'Movimento ridotto', languageEnglish: 'Inglese', languageGerman: 'Tedesco', languageFrench: 'Francese', languageItalian: 'Italiano', languageSpanish: 'Spagnolo', languageCzech: 'Ceco', languagePolish: 'Polacco' }),
  es: makeCatalog({ appSubtitle: 'Laboratorio de movimiento nativo del navegador', previewLive: 'Vista previa activa', localFirst: 'Local primero', visual: 'Visual', style: 'Estilo', audio: 'Audio', layout: 'Diseño', present: 'Presentar', sceneModules: 'Módulos de escena', paletteMood: 'Paleta y ambiente', quickControls: 'Controles rápidos', energy: 'Energía', sensitivity: 'Sensibilidad', live: 'En directo', response: 'Respuesta', overallLift: 'Elevación visual global', audioResponse: 'Curva de respuesta de audio', animationTempo: 'Tempo de animación', detailParticles: 'Detalles y partículas', bloomIntensity: 'Intensidad del brillo', moduleVersion: 'módulo v1.0', chooseMp3Begin: 'Elige un MP3 para empezar', motion: 'Movimiento', density: 'Densidad', glow: 'Brillo', resetScene: 'Restablecer escena', projectName: 'Nombre del proyecto', noAudioSelected: 'No hay audio seleccionado', silencePreview: 'La vista previa funciona en silencio.', chooseLocalMp3: 'Elegir MP3 local', resetAudio: 'Restablecer audio', language: 'Idioma', languageSelector: 'Selector de idioma', fpsTarget: 'Objetivo: 60 FPS', loadMp3: 'Carga un MP3 para que reaccione la escena', playAudio: 'Reproducir audio', pauseAudio: 'Pausar audio', previousPosition: 'Posición anterior', nextPosition: 'Posición siguiente', playbackPosition: 'Posición de reproducción', volume: 'Volumen', stageNote: 'El audio permanece en el navegador. Los controles se guardan localmente; no se requiere carga ni cuenta.', spectrumName: 'Espectro', spectrumDescription: 'Columnas de frecuencia nítidas al ritmo de la señal.', threeDSpectrumName: 'Espectro 3D', threeDSpectrumDescription: 'Sala en perspectiva con paredes espejadas y estelas Ghost.', waveformName: 'Forma de onda', waveformDescription: 'Cinta luminosa con contorno de audio orgánico.', orbitalName: 'Orbital', orbitalDescription: 'Partículas y anillos que crecen con las frecuencias graves.', fluidGlowName: 'Brillo fluido', fluidGlowDescription: 'Nubes lentas de luz para mezclas atmosféricas.', cosmicName: 'Caleidoscopio cósmico', cosmicDescription: 'Caleidoscopio WebGL2 controlado por audio.', auroraName: 'Aurora', auroraDescription: 'Menta fría con señal cálida', emberName: 'Ascua', emberDescription: 'Cobre, coral y medianoche', monoName: 'Monocromo', monoDescription: 'Grafito suave y blanco eléctrico', oceanName: 'Océano profundo', oceanDescription: 'Profundidad azul con borde violeta', landscape: 'Horizontal', portrait: 'Vertical', square: 'Cuadrado', high: 'Alta', balanced: 'Equilibrada', low: 'Baja', reducedMotion: 'Movimiento reducido', languageEnglish: 'Inglés', languageGerman: 'Alemán', languageFrench: 'Francés', languageItalian: 'Italiano', languageSpanish: 'Español', languageCzech: 'Checo', languagePolish: 'Polaco' }),
  cs: makeCatalog({ appSubtitle: 'Pohybová laboratoř nativní v prohlížeči', previewLive: 'Náhled běží', localFirst: 'Nejdříve lokálně', visual: 'Vizualizace', style: 'Styl', audio: 'Audio', layout: 'Rozvržení', present: 'Prezentace', sceneModules: 'Moduly scén', paletteMood: 'Paleta a nálada', quickControls: 'Rychlé ovládání', energy: 'Energie', sensitivity: 'Citlivost', live: 'Živě', response: 'Reakce', overallLift: 'Celkový vizuální zdvih', audioResponse: 'Odezva na audio', animationTempo: 'Tempo animace', detailParticles: 'Detaily a částice', bloomIntensity: 'Intenzita bloom efektu', moduleVersion: 'modul v1.0', chooseMp3Begin: 'Vyberte MP3 pro začátek', motion: 'Pohyb', density: 'Hustota', glow: 'Záře', resetScene: 'Obnovit scénu', projectName: 'Název projektu', noAudioSelected: 'Není vybrané audio', silencePreview: 'Náhled běží potichu.', chooseLocalMp3: 'Vybrat lokální MP3', resetAudio: 'Obnovit audio', audioBrowserHint: 'Audio zůstává v prohlížeči a nikam se nenahrává.', language: 'Jazyk', languageSelector: 'Výběr jazyka', fpsTarget: 'Cíl: 60 FPS', loadMp3: 'Načtěte MP3 a scéna začne reagovat', previewAlreadySilence: 'Náhled už běží potichu.', playAudio: 'Přehrát audio', pauseAudio: 'Pozastavit audio', previousPosition: 'Předchozí pozice', nextPosition: 'Další pozice', playbackPosition: 'Pozice přehrávání', volume: 'Hlasitost', stageNote: 'Audio zůstává v prohlížeči. Ovládání projektu se ukládá lokálně; není potřeba upload ani účet.', spectrumName: 'Spektrum', spectrumDescription: 'Čisté frekvenční sloupce sledující rytmus.', threeDSpectrumName: '3D Spektrum', threeDSpectrumDescription: 'Perspektivní místnost se zrcadlovými stěnami a Ghost stopami.', waveformName: 'Průběh', waveformDescription: 'Svítící stuha s organickým obrysem audia.', orbitalName: 'Orbitální', orbitalDescription: 'Částice a kruhy rostoucí s nízkými frekvencemi.', fluidGlowName: 'Tekutá záře', fluidGlowDescription: 'Pomalé světelné mraky pro atmosférické mixy.', cosmicName: 'Kosmický kaleidoskop', cosmicDescription: 'Kaleidoskop WebGL2 řízený audiem.', auroraName: 'Aurora', auroraDescription: 'Chladná máta s teplým signálem', emberName: 'Žár', emberDescription: 'Měď, korál a půlnoc', monoName: 'Monochromatická', monoDescription: 'Tichá grafitová a elektrická bílá', oceanName: 'Hluboký oceán', oceanDescription: 'Modrá hloubka s fialovým okrajem', landscape: 'Na šířku', portrait: 'Na výšku', square: 'Čtverec', high: 'Vysoká', balanced: 'Vyvážená', low: 'Nízká', reducedMotion: 'Omezený pohyb', languageEnglish: 'Angličtina', languageGerman: 'Němčina', languageFrench: 'Francouzština', languageItalian: 'Italština', languageSpanish: 'Španělština', languageCzech: 'Čeština', languagePolish: 'Polština' }),
  pl: makeCatalog({ appSubtitle: 'Natywne laboratorium ruchu w przeglądarce', previewLive: 'Podgląd działa', localFirst: 'Najpierw lokalnie', visual: 'Wizualizacja', style: 'Styl', audio: 'Audio', layout: 'Układ', present: 'Prezentacja', sceneModules: 'Moduły scen', paletteMood: 'Paleta i nastrój', quickControls: 'Szybkie sterowanie', energy: 'Energia', sensitivity: 'Czułość', live: 'Na żywo', response: 'Reakcja', overallLift: 'Ogólne podniesienie wizualne', audioResponse: 'Krzywa reakcji audio', animationTempo: 'Tempo animacji', detailParticles: 'Detale i cząsteczki', bloomIntensity: 'Intensywność poświaty', moduleVersion: 'moduł v1.0', chooseMp3Begin: 'Wybierz MP3, aby rozpocząć', motion: 'Ruch', density: 'Gęstość', glow: 'Poświata', resetScene: 'Resetuj scenę', projectName: 'Nazwa projektu', noAudioSelected: 'Nie wybrano audio', silencePreview: 'Podgląd działa w ciszy.', chooseLocalMp3: 'Wybierz lokalny MP3', resetAudio: 'Resetuj audio', language: 'Język', languageSelector: 'Wybór języka', fpsTarget: 'Cel: 60 FPS', loadMp3: 'Wczytaj MP3, aby scena zareagowała', playAudio: 'Odtwórz audio', pauseAudio: 'Wstrzymaj audio', previousPosition: 'Poprzednia pozycja', nextPosition: 'Następna pozycja', playbackPosition: 'Pozycja odtwarzania', volume: 'Głośność', stageNote: 'Audio pozostaje w przeglądarce. Sterowanie projektem jest zapisywane lokalnie; upload ani konto nie są wymagane.', spectrumName: 'Widmo', spectrumDescription: 'Wyraźne słupki częstotliwości podążające za pulsem.', threeDSpectrumName: 'Widmo 3D', threeDSpectrumDescription: 'Perspektywiczna sala z lustrzanymi ścianami i zanikającymi śladami Ghost.', waveformName: 'Fala', waveformDescription: 'Świetlista wstęga z organicznym konturem audio.', orbitalName: 'Orbitalne', orbitalDescription: 'Cząsteczki i pierścienie rosnące z niskimi częstotliwościami.', fluidGlowName: 'Płynna poświata', fluidGlowDescription: 'Powolne chmury światła dla atmosferycznych miksów.', cosmicName: 'Kosmiczny kalejdoskop', cosmicDescription: 'Kalejdoskop WebGL2 sterowany dźwiękiem.', auroraName: 'Aurora', auroraDescription: 'Chłodna mięta z ciepłym sygnałem', emberName: 'Żar', emberDescription: 'Miedź, koral i północ', monoName: 'Monochromatyczne', monoDescription: 'Spokojny grafit i elektryczna biel', oceanName: 'Głęboki ocean', oceanDescription: 'Błękitna głębia z fioletową krawędzią', landscape: 'Poziomo', portrait: 'Pionowo', square: 'Kwadrat', high: 'Wysoka', balanced: 'Zrównoważona', low: 'Niska', reducedMotion: 'Ograniczony ruch', languageEnglish: 'Angielski', languageGerman: 'Niemiecki', languageFrench: 'Francuski', languageItalian: 'Włoski', languageSpanish: 'Hiszpański', languageCzech: 'Czeski', languagePolish: 'Polski' }),
};

export const isSupportedLocale = (value: unknown): value is SupportedLocale => typeof value === 'string' && (SUPPORTED_LOCALES as readonly string[]).includes(value);

const SUPPLEMENTAL_TRANSLATIONS: Partial<Record<SupportedLocale, Partial<Catalog>>> = {
  de: { live: 'Live', response: 'Antwort', overallLift: 'Gesamter visueller Hub', audioResponse: 'Audio-Reaktionskurve', animationTempo: 'Animationstempo', detailParticles: 'Details und Partikel', bloomIntensity: 'Bloom-Intensität', moduleVersion: 'Modul v1.0', chooseMp3Begin: 'MP3 zum Starten wählen' },
  fr: { live: 'En direct', response: 'Réponse', overallLift: 'Élévation visuelle globale', audioResponse: 'Courbe de réponse audio', animationTempo: 'Tempo de l’animation', detailParticles: 'Détails et particules', bloomIntensity: 'Intensité de la lueur', moduleVersion: 'module v1.0', chooseMp3Begin: 'Choisir un MP3 pour commencer' },
  it: { live: 'Live', response: 'Risposta', overallLift: 'Sollevamento visivo globale', audioResponse: 'Curva di risposta audio', animationTempo: 'Tempo dell’animazione', detailParticles: 'Dettagli e particelle', bloomIntensity: 'Intensità del bagliore', moduleVersion: 'modulo v1.0', chooseMp3Begin: 'Scegli un MP3 per iniziare' },
  es: { live: 'En directo', response: 'Respuesta', overallLift: 'Elevación visual global', audioResponse: 'Curva de respuesta de audio', animationTempo: 'Tempo de animación', detailParticles: 'Detalles y partículas', bloomIntensity: 'Intensidad del brillo', moduleVersion: 'módulo v1.0', chooseMp3Begin: 'Elige un MP3 para empezar' },
  cs: { live: 'Živě', response: 'Reakce', overallLift: 'Celkový vizuální zdvih', audioResponse: 'Odezva na audio', animationTempo: 'Tempo animace', detailParticles: 'Detaily a částice', bloomIntensity: 'Intenzita bloom efektu', moduleVersion: 'modul v1.0', chooseMp3Begin: 'Vyberte MP3 pro začátek' },
  pl: { live: 'Na żywo', response: 'Reakcja', overallLift: 'Ogólne podniesienie wizualne', audioResponse: 'Krzywa reakcji audio', animationTempo: 'Tempo animacji', detailParticles: 'Detale i cząsteczki', bloomIntensity: 'Intensywność poświaty', moduleVersion: 'moduł v1.0', chooseMp3Begin: 'Wybierz MP3, aby rozpocząć' },
};
export const normalizeLocale = (value: unknown): SupportedLocale => {
  if (isSupportedLocale(value)) return value;
  if (typeof value === 'string') {
    const base = value.toLowerCase().split('-')[0];
    if (isSupportedLocale(base)) return base;
  }
  return 'en';
};

export const detectLocale = (navigatorLike?: Pick<Navigator, 'language' | 'languages'>, storage?: Pick<Storage, 'getItem'>): SupportedLocale => {
  const saved = storage?.getItem(LOCALE_STORAGE_KEY);
  if (isSupportedLocale(saved)) return saved;
  const languages = navigatorLike?.languages?.length ? navigatorLike.languages : [navigatorLike?.language ?? 'en'];
  for (const language of languages) {
    const normalized = normalizeLocale(language);
    if (normalized !== 'en' || language.toLowerCase().startsWith('en')) return normalized;
  }
  return 'en';
};

export const translate = (locale: SupportedLocale, key: TranslationKey, variables: Record<string, string | number> = {}): string => {
  let value = SUPPLEMENTAL_TRANSLATIONS[locale]?.[key] ?? TRANSLATIONS[locale][key] ?? TRANSLATIONS.en[key];
  for (const [name, replacement] of Object.entries(variables)) value = value.replace(`{${name}}`, String(replacement));
  return value;
};

const SCENE_KEY: Record<SceneId, { name: TranslationKey; description: TranslationKey }> = {
  spectrum: { name: 'spectrumName', description: 'spectrumDescription' },
  '3d-spectrum': { name: 'threeDSpectrumName', description: 'threeDSpectrumDescription' },
  waveform: { name: 'waveformName', description: 'waveformDescription' },
  orbital: { name: 'orbitalName', description: 'orbitalDescription' },
  'fluid-glow': { name: 'fluidGlowName', description: 'fluidGlowDescription' },
  'cosmic-kaleidoscope': { name: 'cosmicName', description: 'cosmicDescription' },
  'layered-circles': { name: 'layeredCirclesName', description: 'layeredCirclesDescription' },
};
export const localizeScene = (locale: SupportedLocale, id: SceneId) => ({ name: translate(locale, SCENE_KEY[id].name), description: translate(locale, SCENE_KEY[id].description) });

const PALETTE_KEY: Record<string, { name: TranslationKey; description: TranslationKey }> = {
  aurora: { name: 'auroraName', description: 'auroraDescription' }, ember: { name: 'emberName', description: 'emberDescription' }, mono: { name: 'monoName', description: 'monoDescription' }, ocean: { name: 'oceanName', description: 'oceanDescription' }, ruby: { name: 'rubyName', description: 'rubyDescription' }, emerald: { name: 'emeraldName', description: 'emeraldDescription' }, 'ice-cold': { name: 'iceColdName', description: 'iceColdDescription' },
};
export const localizePalette = (locale: SupportedLocale, id: string) => { const key = PALETTE_KEY[id] ?? PALETTE_KEY.aurora; return { name: translate(locale, key.name), description: translate(locale, key.description) }; };

const PROFILE_NAMES: Record<string, TranslationKey> = {
  'YouTube Landscape': 'youtube', 'YouTube Shorts': 'youtube', 'TikTok Portrait': 'tiktok', 'TikTok Landscape': 'tiktok', 'Instagram Portrait': 'instagram', 'Instagram Square': 'instagram', 'Instagram Landscape': 'instagram', 'Custom 18:9': 'custom',
};
export const localizeProfilePlatform = (locale: SupportedLocale, platform: string) => translate(locale, ({ YouTube: 'youtube', TikTok: 'tiktok', Instagram: 'instagram', Custom: 'custom' } as Record<string, TranslationKey>)[platform] ?? 'custom');
export const localizeOrientation = (locale: SupportedLocale, orientation: string) => translate(locale, ({ Landscape: 'landscape', Portrait: 'portrait', Square: 'square' } as Record<string, TranslationKey>)[orientation] ?? 'landscape');
export const localizeProfileName = (locale: SupportedLocale, name: string) => `${localizeProfilePlatform(locale, name.split(' ')[0])} ${name.includes('Portrait') || name.includes('Shorts') ? localizeOrientation(locale, 'Portrait') : name.includes('Square') ? localizeOrientation(locale, 'Square') : localizeOrientation(locale, 'Landscape')}`;

export const useLocale = () => {
  const [locale, setLocaleState] = useState<SupportedLocale>(() => detectLocale(typeof navigator === 'undefined' ? undefined : navigator, typeof localStorage === 'undefined' ? undefined : localStorage));
  useEffect(() => { try { localStorage.setItem(LOCALE_STORAGE_KEY, locale); } catch { /* storage can be unavailable in private contexts */ } }, [locale]);
  return { locale, setLocale: setLocaleState, t: (key: TranslationKey, variables?: Record<string, string | number>) => translate(locale, key, variables) };
};
